### PR TITLE
fix:add margin on ad after tiles, adjust the width of the iframe

### LINKED ISSUE #278: fix : ad margin with tiles and width overflow
### issue1 -- lose margin:
image

### issue2 -- width overflow
Screenshot 2023-07-27 at 8 41 39 AM

### PR DESCRIPTION
**Pull request by FentPams**
Fix #278 
Screenshot 2023-07-27 at 9 48 40 AM
Screenshot 2023-07-27 at 9 49 12 AM

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After:
  - https://issue-278--petplace--hlxsites.hlx.page/

### CODE REVIEW

**Comment by FentPams** [comment]
@mfrisbey  Hi Mark, I adjusted the width of the ads to avoid overflow, while the ads itself will be cut off when screen shrink, any better idea on doing this? Thank you.

**Comment by mfrisbey** [comment]
@FentPams are you refreshing the page after the screen shrinks? As far as I know, Google selects the ad based on the initial screen size, and doesn't select a different ad as the window is resized.

**Comment by FentPams** [comment]
> @FentPams are you refreshing the page after the screen shrinks? As far as I know, Google selects the ad based on the initial screen size, and doesn't select a different ad as the window is resized.

@mfrisbey  no, I didn't refresh, but shrink the screen size manually, so the ads is not re-selected and cause the width overflow. Does this case we need to handle? 
And, I am also wondering how the ads are loaded, seems not every time of page load, the ads will be loaded.
Thank you

**Comment by mfrisbey** [comment]
> no, I didn't refresh

As long as the overflow is fixed (or the ad disappears) after refreshing the screen, I think that will be enough.

> shrink the screen size manually... this case we need to handle?

IMO, no. We, as developers, are resizing the screen manually a lot because we're testing, but I don't think the average user is going to do this. Especially on mobile devices where the screen size is fixed. It's always good practice to try to handle this, but if we tried to request a different ad every time the `resize` event fires, we would probably exceed our quota for Google's ad API :)

> I am also wondering how the ads are loaded, seems not every time of page load

We depend on the Google ads API for this. I've also noticed that sometimes the ads appear, and sometimes they don't. The API seems very flaky that way. It could also be that we're not using the API correctly (this is the first time Julien or I have worked with Google ads), so maybe it would be good to have another set of eyes look at it, too :)

**Comment by FentPams** [comment]
@mfrisbey  Could you review it and help to merge the code, I only add margin on top of the ad-wrapper, and revert the changes on iframe width. Thank you.
I'll also take a look at the google ads and to see if any possible cause of inconsistent loading.

**Comment by ramboz** [comment]
>  I've also noticed that sometimes the ads appear, and sometimes they don't. The API seems very flaky that way.

@mfrisbey My understanding is that petplace is selling the ad slots to its partners. If there is a bid on the slot, we will have an ad, but if no one payed for it then you won't have anything. Ultimately, as popularity grows, we will likely always have ads 😄

**Pull request closed without merging**
