### PR TITLE
chore: try optimized font loading for smoother UX

### LINKED ISSUE #274: chore: try optimized font loading for smoother UX

### PR DESCRIPTION
**Pull request by ramboz**
Track if fonts have previously been loaded and cached by the browser so we can speed up the loading on subsequent visits. If the browser cache is not disabled, this should remove the flickering from the font swap when you navigate across pages.

This ultimately helps improve LCP, TTI and SI scores.

Fix #274 

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After:
  - https://issue-274--petplace--hlxsites.hlx.page/
  - https://issue-274--petplace--hlxsites.hlx.page/?martech=off

### CODE REVIEW

**Comment by FentPams** [comment]
Wow, looks good!! 👍

**Comment by FentPams** [comment]
Might be a dumb question: then why we need a separate fonts css if they will adding toll?

**Comment by ramboz** [comment]
When you switch pages, there is a visual flicker when the font is applied. This is mostly visible on the hero:
Screenshot 2023-08-04 at 8 27 49 AM
Screenshot 2023-08-04 at 8 27 56 AM

With this change, we reduce that effect by loading the fonts definitions sooner once the actual font files are cached. This gives the end user a more stable experience with less shifting. The tradeoff is that we do add another roundtrip to fetch a new CSS file (fonts.css) and this adds 40~50ms delay.

**Comment by ramboz** [comment]
#288  has a better implementation of this that has less impact

**Pull request closed without merging**
