### PR TITLE
Datalayer implementation for category, search and newsletter

### PR DESCRIPTION
**Pull request by ankyc-phi**
Branch Commits :
- tracking search in header (ppl-17)
- tracking search in home page (ppl-17)
- tracking newsletter signups (ppl-23)
- tracking content category (ppl-25)
- added linting rule for default export
- importing function into files
- helper function to push to layer
- using proper terminology for layer

Jira Issues :
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-17
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-25
https://pethealthinc.atlassian.net/jira/software/c/projects/PPL/boards/35?selectedIssue=PPL-23

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After:
  - https://datalayer-ppl-17-23-25--petplace--hlxsites.hlx.page/
  - https://datalayer-ppl-17-23-25--petplace--hlxsites.hlx.page/?martech=off

### CODE REVIEW

**Review by mfrisbey — COMMENTED** [review]
Seems pretty straightforward to me. The only thing from a nitpicky coding standpoint could be that we create another function in `datalayer.js`:

```
window.dataLayer ||= [];
export function addDataLayer(layer) {
    window.dataLayer.push(layer);
}
```

Then you import and call that everywhere:

```
import { addDataLayer } from '../scripts/datalayer.js';
...
addDataLayer({
  event: 'search',
  search_term: query,
});
```
That might help cut down on some of the copy/pasted code, but isn't a huge deal.

**Comment by ankyc-phi** [comment]
going back to PSI, seems to have a higher number than originally tested (please view below) - how can we retest this now?
https://pagespeed.web.dev/analysis/https-datalayer-ppl-17-23-25--petplace--hlxsites-hlx-page/bf40gforb6?form_factor=mobile

**Review by mfrisbey — APPROVED** [review]
Looks great!

**Comment by mfrisbey** [comment]
Next step would be to merge the PR, which will deploy the change to petplace.com

**Pull request merged**
