### PR TITLE
feat: implement write-for-us

### LINKED ISSUE #276: feat: implement https://www.petplace.com/write-for-us/
Image

Image

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by FentPams**
Fix #276 

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/write-for-us
- After: https://write-for-us--petplace--hlxsites.hlx.page/write-for-us

#### Clicking the arrow-down button, will directs to the form section
Screenshot 2023-07-26 at 4 35 24 PM

#### Collecting input infor[ here](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/petplace/drafts/xfeng/email-us.xlsx?d=w5eb5f1d2cf6c43009986ffbc555bb29c&csf=1&web=1&e=QoRRcg)
Screenshot 2023-07-27 at 11 40 19 AM

### CODE REVIEW

**Comment by FentPams** [comment]
The spreadsheet for  "email-us" is [here](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/petplace/drafts/xfeng/[email-us.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/petplace/drafts/xfeng/email-us.xlsx?d=w5eb5f1d2cf6c43009986ffbc555bb29c&csf=1&web=1&e=wJwTg8)?d=w5eb5f1d2cf6c43009986ffbc555bb29c&csf=1&web=1&e=wJwTg8), I am wondering shall we combine it with contacts.xlsx or leaving them as separate two.

**Review by ramboz — COMMENTED** [review]
Looks overall good to me!

To bring this to the finish line, I would:
1. add a new "pattern" column to the spreadsheet for the fields definition
2. set a regexp pattern for the email field that checks for valid input
3. update the `form.js` block to add the `pattern` attribute if the field definition has it
4. Move both spreadsheet and page back to the root of the project
5. preview + publish everything

**Comment by FentPams** [comment]
> 1. add a new "pattern" column to the spreadsheet and set the regexp pattern, and title message ✅

Screenshot 2023-08-10 at 1 14 27 AM

> 2. update the `form.js` block to add the `pattern` attribute if the field definition has it ✅

> 3. Move both spreadsheet and page back to the root of the project, preview + publish ✅


### ❓ Do they need Slack notification for this?  Currently is added:
Screenshot 2023-08-10 at 1 38 06 AM


### Example with invalid email:
Screenshot 2023-08-10 at 1 22 51 AM

**Comment by ramboz** [comment]
👏🏼 perfect! and yes, we can keep slack notifications for now

**Comment by FentPams** [comment]
Thank you for confirming that. @ramboz  I am also thinking about checking valid messages, do you think it is necessary or possible for doing that? Like adding a word limit, at least a two-word count, such as this.  Haha, hope GPT can be here as well, have some instant response. (Just brainstorming...)🤔

**Comment by ramboz** [comment]
That is a good point. We could theoretically assume that a name is at least 2 letters, and a message at least, say, 10.

Now, I would keep a few things in mind:
1. client-side validation will not prevent tech-savvy people from bypassing the checks. they can just edit the HTML tags and bypass the whole logic
2. validating an email field is typically important because it's a "technical" value and prone to be mistyped, and since it's the only way to contact the person back, we want to make sure it's as accurate as possible
3. making assumptions on name lengths isn't always great… I've met people who only had a single letter in either first or last name… so validation may end up being an inconvenience in some edge cases.

Personally, I'd stick to what you have here and wait for the customer to request adjustments if needed before over-engineering this

**Review by ramboz — APPROVED** [review]

**Pull request merged**
