### PR TITLE
feat: add author info block

### LINKED ISSUE #46: feat: full user info block
Image

### PR DESCRIPTION
**Pull request by mfrisbey**
Fix #46

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.page/
- After: https://issue-46--petplace--hlxsites.hlx.page/

Adds a new template (incomplete) for an "ask author" page. The very basic layout for the template is in place - for now it's very similar to the category info template.

The main task was to add a block for displaying an author's avatar and name. The block is responsive, so it will change depending on screen resolution. See newly added page:

- https://issue-46--petplace--hlxsites.hlx.page/tags/ask-dr-debra-common-questions

### CODE REVIEW

**Comment by ramboz** [comment]
I seem to see a bit of CLS. Might be worth debugging and double-checking.

**Comment by ramboz** [comment]
Looks overall good… CLS aside 😉

**Comment by mfrisbey** [comment]
@ramboz wow, you're fast :)

I noticed the CLS too, will take a look. Thanks!

**Review by travrob1 — APPROVED** [review]

**Comment by mfrisbey** [comment]
@ramboz the high CLS was because the page layout was only a placeholder (there was some very large heading text that was causing the shift), so I just went ahead and fleshed out the page's template. CLS is now fixed, and that page is mostly done!

**Pull request merged**
