### PR TITLE
08/26 phase2 release

### PR DESCRIPTION
**Pull request by darlantc**
This release includes some finished features for Phase 2:

My Pets
Pet profile
Pet watch benefits
Pet documents
Pet edit form
Lost pet form
Found pet form
Pet profile onboarding Dialog

Test URLs:

Before: https://main--petplace--hlxsites.hlx.page/
After:
https://08-26-phase2-release--petplace--hlxsites.hlx.page/
https://08-26-phase2-release--petplace--hlxsites.hlx.page/?martech=off

### CODE REVIEW

**Comment by ankyc-phi** [comment]
@ramboz i'm currently taking a look but would be good to another pair of eyes to validate as well if you have time :)

**Review by ramboz — CHANGES_REQUESTED** [review]
I see a few issues that I would consider not following our best practices:
1. use of "tabs" instead of "4 spaces" through the code now. This is a change in codestyle and prone to having code indentation problems down the road
2. use of png images. EDS recommends using SVG icons as those are typically more performant and can be easily sized to the context they are used in
Please revert the "4 spaces" to "tab" replacement in the files… this just adds noise to the PR and is likely to affect how code is rendered in different IDEs.

I would also make sure to specifically run a performance audit on those react pages a bit since the PR won't do it for you.

**Comment by darlantc** [comment]
> I see a few issues that I would consider not following our best practices:
> 
> 1. use of "tabs" instead of "4 spaces" through the code now. This is a change in codestyle and prone to having code indentation problems down the road
> 2. use of png images. EDS recommends using SVG icons as those are typically more performant and can be easily sized to the context they are used in
>    Please revert the "4 spaces" to "tab" replacement in the files… this just adds noise to the PR and is likely to affect how code is rendered in different IDEs.
> 
> I would also make sure to specifically run a performance audit on those react pages a bit since the PR won't do it for you.

Thanks for noticing the "4 spaces" to "tabs" changes!
It wasn't a planned change, so I reverted it.

I'll talk with the team about the PNG vs SVG image suggestion and I'll change those in the next release.

**Review by ankyc-phi — APPROVED** [review]
looks great, except for few comments left about folder structure but not really tech debt so can be ignored

**Pull request merged**
