### PR TITLE
Styling for Insurance Landing Page

### PR DESCRIPTION
**Pull request by Tom-Scott-Hero**
Branch Commits:

- Pushing Initial Insurance Landing Page Styles
- Mobile Fixes
- Adding more mobile/tablet styles
- Updating Responsive Styles
- datalayer tracking in lazy phase
- adding some changes to center content
- removing main selector as it's no longer needed
- Responsive Updates to insurance landing page

Jira Issue:
https://pethealthinc.atlassian.net/browse/PPL-31

Test URLs:

- Before: 
     https://main--petplace--hlxsites.hlx.page/pet-insurance
- After:
     https://insurance-landing--petplace--hlxsites.hlx.page/pet-insurance

### CODE REVIEW

**Review by mfrisbey — COMMENTED** [review]
I'll approve it if you'd like, but there seems to be some incorrect block implementation, which is causing a lot of 404's in the console. For example, there are `subhead`, `reasons`, and `insurance` blocks in the word document, but there is no corresponding code for those. Normally, to implement these we would create this file structure:

```
blocks
..subhead
....subhead.css
....subhead.js
..reasons
....reasons.css
....reasons.js
..insurance
....insurance.css
....insurance.js
```

Then we would add CSS specific to a block in its corresponding `*.css` file. It looks like we've got all the block styles in `insurance-landing-page.css`, whereas normally they would be separated into the block files.

The way it is _works_, but we've got 404's in the console, and blocks that couldn't be reused on other pages because all the block styles are in the template instead of the block files.

**Review by ramboz — APPROVED** [review]
I do agree with @mfrisbey recommendations on re-using variables and px vs rem, but this isn't a blocker and ultimately down to your preferences maintaining the codebase long-term… the block implementations and 404 are more a concern since they will negatively impact performance and possibly ranking because we have errors in the browser logs essentially

**Comment by mfrisbey** [comment]
Thanks @Tom-Scott-Hero - looks great! The last thing to check is that the lint workflow is failing. You can see the errors locally by running the command `npm run lint` in the root directory. After you've fixed those and the workflows are green, we'll be ready to merge!

**Comment by Tom-Scott-Hero** [comment]
@mfrisbey Thanks! I just pushed an update with the linter corrections. Let me know if there are any other changes needed.

**Review by mfrisbey — APPROVED** [review]
Thanks!

**Pull request merged**
