### PR TITLE
PM#116 - PPL: Aggregator - Data Layer Enablement

### PR DESCRIPTION
**Pull request by shiv-pethealth**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Jira Ticket - [PM#116](https://pethealthinc.atlassian.net/browse/PM-116)

Test URLs:
- Before: https://main--petplace--hlxsites.hlx.live/
- After:
  - https://pm-116-datalayer-enablement--petplace--hlxsites.hlx.live/
  - https://pm-116-datalayer-enablement--petplace--hlxsites.hlx.live/?martech=off

### CODE REVIEW

**Review by ankyc-phi — APPROVED** [review]

**Comment by ankyc-phi** [comment]
@ramboz i'm not able to determine why the performance score seems to be stuck around the 65 mark, but it doesn't look like there have been significant changes that are going in to cause this problem - the checks are passing, but i just want to make sure that we're not putting any bad code on the branch

**Comment by ramboz** [comment]
@ankyc-phi You ran the test against the `.hlx.page` URLs which are not fully optimized, and I'm thinking you had a bad run with big martech impact on top of that

**Comment by shiv-pethealth** [comment]
@ankyc-phi @ramboz So, we are good to merge this right?

**Comment by ramboz** [comment]
@shiv-pethealth Yes! Nothing blocking on my end.

**Pull request merged**
